services:
  - type: web
    name: lab-aggregator-backend
    env: node
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.0.0
      - key: MONGODB_URI
        sync: false
      - key: CLIENT_ORIGIN
        sync: false
